[package]
name = "pijama_core"
version = "0.1.0"
authors = ["The Pijama Project Developers"]
edition = "2018"

[dependencies]
thiserror = "1.0"
nom = "5.1.1"
nom_locate = "2.0.0"
once_cell = "1.4.0"
pijama_ast = { path = "../pijama_ast", version = "0.1.0" }
